# Generated by Django 3.2.5 on 2021-09-22 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('post_kind', models.CharField(blank=True, choices=[('BLOG', 'BLOG'), ('ADVERTISING', 'ADVERTISING'), ('NEWS', 'NEWS')], max_length=11, null=True, verbose_name='post')),
                ('is_moderated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'order_with_respect_to': 'author',
            },
        ),
    ]
